### ISSUE TITLE
Crash on startup with PostGIS enabled PostgreSQL 14

### ISSUE THREAD

**Issue by claudiobgit** [notum-cz/strapi-plugin-location#20]
### Describe the bug

When PostGIS is already enabled on server, Strapi crashes on startup in developing environment (not tested in production).
This happens after enabling the plugin and adding the custom field to a collection, Strapi could not start and logs show the following:
```
[2023-08-08 18:57:53.332] info: Error Enabling PostGIS, create extension postgis; - extension "postgis" already exists
[2023-08-08 18:57:53.351] error: Error accessing POSTGIS
Error: Could not find Custom Field: plugin::location-plugin.location
```

On the server side, the Postgres logs show:
```
2023-08-08 17:22:32.530 UTC [476909] strapi@develop_strapi ERROR:  function postgis_version() does not exist at character 8
2023-08-08 17:22:32.530 UTC [476909] strapi@develop_strapi HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-08-08 17:22:32.530 UTC [476909] strapi@develop_strapi STATEMENT:  SELECT PostGIS_version();
2023-08-08 17:22:32.547 UTC [476909] strapi@develop_strapi ERROR:  extension "postgis" already exists
2023-08-08 17:22:32.547 UTC [476909] strapi@develop_strapi STATEMENT:  create extension postgis;
2023-08-08 17:22:32.566 UTC [476909] strapi@develop_strapi ERROR:  function postgis_version() does not exist at character 8
2023-08-08 17:22:32.566 UTC [476909] strapi@develop_strapir HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-08-08 17:22:32.566 UTC [476909] strapi@develop_strapir STATEMENT:  SELECT PostGIS_version();
2023-08-08 17:22:32.748 UTC [476909] strapi@develop_strapi LOG:  could not receive data from client: Connection reset by peer
```

### Steps to reproduce the behavior

1. Install the strapi-plugin-location following documentation
2. Execute `npm install && npm run build && npm run develop`
3. Access the Strapi dashboard and add the custom field provided by the plugin to a collection, Strapi restarts

### Expected behavior

Strapi should restart properly.

### System

- Node.js version: v18.17.0
- NPM version: v9.6.7
- Strapi version: v4.12.1
- Database: PostgreSQL 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu
- PostGIS version: v3.2.0
- Operating system: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-78-generic x86_64)

### Additional context

PostGIS has its own 'postgis' scheme enabled on the db, Strapi uses the 'public' scheme. The 'search_path' on the database is configured with 'public, postgis' values. 

Running the command 'SELECT postgis_full_version();' on the database properly returns PostGIS version:
`POSTGIS="3.2.0 c3e3cc0" [EXTENSION] PGSQL="140" GEOS="3.10.2-CAPI-1.16.0" PROJ="8.2.1" LIBXML="2.9.12" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)"`

**Comment by omikulcik** [comment]
Hello @claudiobgit, thank you for reporting this issue. I will try to replicate it and get back to you.

**Comment by omikulcik** [comment]
I am using this image https://registry.hub.docker.com/r/postgis/postgis/tags?page=1 and I can't find version 3.2.0 there. Are you sure that is the correct version? I assume the image has a different versioning.

**Comment by claudiobgit** [comment]
> I am using this image https://registry.hub.docker.com/r/postgis/postgis/tags?page=1 and I can't find version 3.2.0 there. Are you sure that is the correct version? I assume the image has a different versioning.

I am not running a Docker image for PostgreSQL but I am sure of the running version that I get with:
`SELECT * FROM pg_available_extensions WHERE name = 'postgis';`
```
  name   | default_version | installed_version |                          comment                           
---------+-----------------+-------------------+------------------------------------------------------------
 postgis | 3.2.0           | 3.2.0             | PostGIS geometry and geography spatial types and functions
```
I will try to dig deeper in the plugin and post any advance here.

**Comment by omikulcik** [comment]
Thank you, I am unfortunately not able to replicate your setup easily.

**Comment by claudiobgit** [comment]
The problem should be considered solved after having manually granted UC privileges to PUBLIC on 'postgis' schema in the database @omikulcik

**Comment by omikulcik** [comment]
Ok, so I am closing this issue. Thank you @claudiobgit

**Comment by emaddoma** [comment]
I've just run into a very similar issue on my end after attempting to deploy to Heroku.  Everything worked fine on my local.

PG 15.4.  
Strapi 4.12.7. 

@claudiobgit What is UC privleges?

```
2023-08-31T19:37:37.223489+00:00 app[web.1]: [2023-08-31 19:37:37.221] info: Error Enabling PostGIS, no pg_hba.conf entry for host "44.201.222.159", user "qhxyadnfszkhvb", database "d2km56udn7ts5g", no encryption
2023-08-31T19:37:37.238511+00:00 app[web.1]: [2023-08-31 19:37:37.238] error: Error accessing POSTGIS
2023-08-31T19:37:37.243644+00:00 app[web.1]: [2023-08-31 19:37:37.243] debug: ⛔️ Server wasn't able to start properly.
2023-08-31T19:37:37.243848+00:00 app[web.1]: [2023-08-31 19:37:37.243] error: Could not find Custom Field: plugin::location-plugin.location
2023-08-31T19:37:37.243852+00:00 app[web.1]: Error: Could not find Custom Field: plugin::location-plugin.location
2023-08-31T19:37:37.243852+00:00 app[web.1]: at Object.get (/app/node_modules/@strapi/strapi/lib/core/registries/custom-fields.js:34:15)
2023-08-31T19:37:37.243861+00:00 app[web.1]: at convertCustomFieldType (/app/node_modules/@strapi/strapi/lib/utils/convert-custom-field-type.js:15:67)
2023-08-31T19:37:37.243861+00:00 app[web.1]: at Strapi.register (/app/node_modules/@strapi/strapi/lib/Strapi.js:409:5)
2023-08-31T19:37:37.243861+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-31T19:37:37.243862+00:00 app[web.1]: at async Strapi.load (/app/node_modules/@strapi/strapi/lib/Strapi.js:492:5)
2023-08-31T19:37:37.243862+00:00 app[web.1]: at async Strapi.start (/app/node_modules/@strapi/strapi/lib/Strapi.js:218:9)
2023-08-31T19:37:37.526141+00:00 heroku[web.1]: Process exited with status 1
2023-08-31T19:37:37.557614+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by emaddoma** [comment]
I figured it out.  I was missing a strapi config for the environment.
